name: Feature request
# Use the same formate as https://github.com/dhslab/nf-core-wgsnano (2024-12-10)
## TO DO
description: Suggest an idea for the nf-core/wgsnano pipeline
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: Please describe your suggestion for a new feature. It might help to describe a problem or use case, plus any alternatives that you have considered.
    validations:
      required: true
